services:

  mysql:
    image: mysql:8.0
    container_name: activity_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clover@123
      MYSQL_DATABASE: activity_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build: .
    container_name: activity_django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_NAME: activity_db
      DB_USER: root
      DB_PASSWORD: clover@123
      DB_HOST: mysql
      DB_PORT: 3306

volumes:
  mysql_data:
