---
- name: Deploy Playbook
  hosts: localhost
  connection: local

  vars:
    activity: ""

  tasks:
    - name: Echo deploy activity
      debug:
        msg: "Deploy process started for: {{ activity }}"
