---
- name: Restart Playbook
  hosts: localhost
  connection: local

  vars:
    activity: ""

  tasks:
    - name: Echo restart activity
      debug:
        msg: "Restart initiated for: {{ activity }}"
